const mongoose = require('mongoose');
const {Schema} = mongoose;

const DienteSchema = new Schema({
    Nombre: {type: String, required: true},
    Apellido: {type: String, required: true},
    Usuario: {type: String, required: true},
    IDUSUARIO: {type: String, required: true},
    IDDOCTOR: {type: String, required: true},
    ICSD: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    ILSD: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    CSD: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    PPSD: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    SPSD: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    PMSD: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    SMSD: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    TMSD: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    ICSI: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    ILSI: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    CSI: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    PPSI: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    SPSI: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    PMSI: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    SMSI: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    TMSI: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    ICII: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    ILII: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    CII: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    PPII: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    SPII: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    PMII: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    SMII: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    TMII: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    ICID: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    ILID: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    CID: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    PPID: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    SPID: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    PMID: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    SMID: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    TMID: {type: String, required: true, default:'El diente se encuentra en buen estado'},
    Date: {type: Date, default: Date.now},
});

module.exports = mongoose.model('Diente',DienteSchema);